#######################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  data:
    jpa:
      repositories:
        enabled: true

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=master;username=sa;password=z!oBx1ab;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: z!oBx1ab
    initialization-mode: always

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  sql:
    init:
      mode: always
